package processing.test.phase_iv;

/* autogenerated by Processing revision 1292 on 2023-06-13 */
import processing.core.*;
import processing.data.*;
import processing.event.*;
import processing.opengl.*;

import java.util.HashMap;
import java.util.ArrayList;
import java.io.File;
import java.io.BufferedReader;
import java.io.PrintWriter;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.IOException;

public class PHASE_IV extends PApplet {

float airspeed = 0;
float avion;
float avionhb;
float subspeed = 0;
float sub;
float subhb; 
PImage imgav;
PImage imgsub;
float xb;
float yb;
float x1;
float bspeed;
float pspeed;
float bomb;
float proy;
boolean click;
boolean clicks;
float t=0;
int control = 0;


public void setup(){
  /* size commented out by preprocessor */;
  avion=0;
  sub=1600;
  //sub=738;
  imgav = loadImage("avionD.png");
  imgsub = loadImage("submarinoD.png");
  bomb = height/3;
}

public void draw() {
  PImage img;
  img = loadImage("backgroundD.jpg");
  background(img);
 image(imgav, avion, height/3, 200, 100); //avion
 image(imgsub, sub, (height*2/3), 200, 100);    //submarino
 
 airspeed = 10;
 subspeed = -10;
 
 avion = avion + airspeed;
 avionhb = avion + 250;
 //println("" + avion, height/3);
 sub = sub + subspeed;
 subhb = sub + 250;
//println("x = " + mouseX +", y = "+ mouseY);
 
 if(avion > width){
   avion = 0;
 }
 if(sub < 0){
  sub=1600; 
 }
  
  
 if(control==1){
  xb = avion;
  //text (xb, yb, 40, 120);
  bspeed = bspeed + 2;
  bomb = bomb + bspeed;
  ellipse(xb, bomb, 32, 32);
  if(bomb>738){
     control=0;
     
   }
 }
 
 if(control==2){
  xb = sub;
  pspeed = pspeed - 10;
  proy = 500;
  proy = proy + pspeed;
  ellipse(xb, proy, 32, 32);
  /*if(proy < 230){
    pspeed = pspeed + 20;
    proy = 230;
    proy = proy + pspeed;
    ellipse(xb, proy, 32, 32);
  }*/
  
  //control = 0;
 }
    
}

public void mouseClicked(){
  if(mouseX > avion && mouseX < avionhb  && mouseY > 230 && mouseY < 348 /*&& mousePressed*/){
    /*println("avion"); 
    println("x: " + mouseX, " y: " + mouseY);
    println("avion : " + avion, "avionhb: " + avionhb);*/
    control = 1;
 }else if(mouseX > sub && mouseX < subhb && mouseY > 500 && mouseY < 599 /*&& control == 0*/){
    /*println("sub"); 
    println("x: " + mouseX, " y: " + mouseY);
    println("sub : " + sub, "subhb: " + subhb);*/
    control = 2;
    
    
 }
  
}

/*
class avionhb
{
  float x, y;
  avionhb.x=(float _x){
    x = _x;
  } 
}*/


  public void settings() { size(1600, 738); }

  static public void main(String[] passedArgs) {
    String[] appletArgs = new String[] { "PHASE_IV" };
    if (passedArgs != null) {
      PApplet.main(concat(appletArgs, passedArgs));
    } else {
      PApplet.main(appletArgs);
    }
  }
}
